const data = {
  "login": "gui3",
  "id": 45894433,
  "node_id": "MDQ6VXNlcjQ1ODk0NDMz",
  "avatar_url": "https://avatars1.githubusercontent.com/u/45894433?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/gui3",
  "html_url": "https://github.com/gui3",
  "followers_url": "https://api.github.com/users/gui3/followers",
  "following_url": "https://api.github.com/users/gui3/following{/other_user}",
  "gists_url": "https://api.github.com/users/gui3/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/gui3/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/gui3/subscriptions",
  "organizations_url": "https://api.github.com/users/gui3/orgs",
  "repos_url": "https://api.github.com/users/gui3/repos",
  "events_url": "https://api.github.com/users/gui3/events{/privacy}",
  "received_events_url": "https://api.github.com/users/gui3/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Guillaume SILVENT",
  "company": null,
  "blog": "https://gui3.herokuapp.com/",
  "location": "Lyon, FR",
  "email": null,
  "hireable": true,
  "bio": ":chestnut: \r\nold accout : @Gui38 ",
  "twitter_username": null,
  "public_repos": 28,
  "public_gists": 0,
  "followers": 0,
  "following": 1,
  "created_at": "2018-12-15T09:46:29Z",
  "updated_at": "2020-07-29T18:57:42Z"
}

export default data
